---
deployment:
  tasks:
    - export DEPLOYPATH=/home/buddydev/coppelman.buddydevs.com
    - export PATH=$PATH:/usr/local/bin:/usr/bin:/opt/cpanel/ea-nodejs20/bin
    - npm install
    - npm run build
    - cp -r dist/. $DEPLOYPATH
    - cp .htaccess $DEPLOYPATH/.htaccess
