---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html
    - /bin/npm install
    - /bin/npm run build
    - /bin/cp -r dist/. $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
